version: '3'
services: 
    node:
      build:
        dockerfile: ./config/Dockerfile
        context: .
      image: marcobneves/node-application
      container_name: node-application
      ports: 
        - "3000:3000"
      networks: 
        - my-network

    # Implement db
    # Implement other services

networks: 
  my-network:
    driver: bridge



